Terraform -> terraform-2
Otus-DevOps-2023-03/russo1982_infra pull request #7
Opened 2023-05-15 19:35 UTC by russo1982

# Выполнено ДЗ №

 - [ ] Принципы организации инфраструктурного кода и работа над инфраструктурой в команде на примере
 - [ ] Задание со *

## В процессе сделано:
 - Разделение в модули
 - Применение связности инстансов

Но, прошу проверить результат скрипта test

Скрипт жалуется на packer json файлы и переменную db_ip хотя он объявлен во всех файлах variables.tf

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2023-05-16 08:56 UTC, mrgreyves requested changes
Здравствуйте!)
По пакеру - не хватает пустых строк в конце файлов, правится быстро =)
По поводу адреса базы - проверяйте везде ли где надо указана и передается переменная

2023-05-16 08:56 UTC, mrgreyves commented on terraform/prod/main.tf
> +  ##depends_on      = [module.db]
Зачем закомментировали зависимости?)

2023-05-16 12:14 UTC, russo1982 commented on terraform/prod/main.tf
> +  ##depends_on      = [module.db]
test скрипт выдавал ошибку.

2023-05-17 13:53 UTC, mrgreyves approved these changes
Здравствуйте!)
Про depends_on можно почитать вот тут https://itnext.io/beware-of-depends-on-for-modules-it-might-bite-you-da4741caac70
ДЗ принимаю =)

2023-05-18 10:30 UTC, merged